### ISSUE TITLE
Getting Bootstrap

### ISSUE THREAD

**Issue by guilhermearmelo** [dieegom/brumadinho_location#23]
Try getting bootstrap from getbootstrap.com
Add:

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

on index.html. The css folder is not making the app faster, but slower.

**Comment by glauberfc** [comment]
I think React can be a good choice

**Comment by qgustavor** [comment]
@glauberfc I'm fine with React, but I find Vue's "incrementally adoptable" good for this project as we can just add a `<script>` for now instead of requiring to add a build step to compile JSX or [having to avoid it](https://reactjs.org/docs/react-without-jsx.html).

**Comment by vaniaon** [comment]
Guys,

Since now we have a list of independents projects, I think we can use frontend technologies that the first front dev who take the project are more familiar with. The idea is using microservices and devops technologies for integrate them. 
As I wrote in the readme, once you are working on a project, this put a comment there for everyone know.

I am closing this issue.
